language: node_js
node_js:
  - "10"
cache: yarn
install:
  - yarn
script:
  - yarn test
  # - yarn 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master