language: node_js
node_js:
  - "10"
cache: yarn
install:
  - yarn
script:
  - yarn test
  - yarn build
deploy:
  provider: script
  script: netlify deploy -s optimistic-poitras-394703 -t $NETLIFY_PUBLISH_KEY -p ./dist
  skip_cleanup: true
  on:
    branch: master