language: node_js
node_js:
  - "10"
cache: yarn
install:
  - yarn
script:
  - yarn test

before_deploy:
  - yarn add netlify-cli -g
  - yarn build

deploy:
  provider: script
  script: netlify deploy --site $NETLIFY_SITE_API --auth $NETLIFY_PUBLISH_KEY --dir ./dist
  skip_cleanup: true
  on:
    branch: master